// Built-in staples library: common ingredients, USDA-style approximate values.
// Anything not here can be found via Open Food Facts search or quick-added by hand.
export const FOODS = [
  { id: 'f1', name: 'Oatmeal, cooked', brand: 'Generic', serving: '1 cup', calories: 154, protein: 6, carbs: 27, fat: 3, fiber: 4, sugar: 1, sodium: 9, cat: 'Breakfast' },
  { id: 'f2', name: 'Greek Yogurt, plain nonfat', brand: 'Generic', serving: '1 cup', calories: 130, protein: 22, carbs: 9, fat: 0, fiber: 0, sugar: 7, sodium: 65, cat: 'Breakfast' },
  { id: 'f3', name: 'Banana', brand: 'Generic', serving: '1 medium', calories: 105, protein: 1, carbs: 27, fat: 0, fiber: 3, sugar: 14, sodium: 1, cat: 'Fruit' },
  { id: 'f4', name: 'Chicken Breast, grilled', brand: 'Generic', serving: '6 oz', calories: 281, protein: 53, carbs: 0, fat: 6, fiber: 0, sugar: 0, sodium: 126, cat: 'Protein' },
  { id: 'f5', name: 'Brown Rice, cooked', brand: 'Generic', serving: '1 cup', calories: 216, protein: 5, carbs: 45, fat: 2, fiber: 4, sugar: 1, sodium: 10, cat: 'Grains' },
  { id: 'f6', name: 'Salmon, baked', brand: 'Generic', serving: '6 oz', calories: 367, protein: 40, carbs: 0, fat: 22, fiber: 0, sugar: 0, sodium: 116, cat: 'Protein' },
  { id: 'f7', name: 'Whole Wheat Bread', brand: 'Generic', serving: '2 slices', calories: 160, protein: 8, carbs: 28, fat: 2, fiber: 4, sugar: 4, sodium: 260, cat: 'Grains' },
  { id: 'f8', name: 'Peanut Butter', brand: 'Generic', serving: '2 tbsp', calories: 190, protein: 8, carbs: 7, fat: 16, fiber: 2, sugar: 3, sodium: 140, cat: 'Fats' },
  { id: 'f9', name: 'Egg, large', brand: 'Generic', serving: '1 egg', calories: 72, protein: 6, carbs: 0, fat: 5, fiber: 0, sugar: 0, sodium: 71, cat: 'Protein' },
  { id: 'f10', name: 'Almonds', brand: 'Generic', serving: '1 oz (23)', calories: 164, protein: 6, carbs: 6, fat: 14, fiber: 4, sugar: 1, sodium: 0, cat: 'Snacks' },
  { id: 'f11', name: 'Protein Shake, whey', brand: 'Generic', serving: '1 scoop', calories: 120, protein: 24, carbs: 3, fat: 1, fiber: 0, sugar: 2, sodium: 50, cat: 'Protein' },
  { id: 'f12', name: 'Avocado', brand: 'Generic', serving: '1/2 medium', calories: 161, protein: 2, carbs: 9, fat: 15, fiber: 7, sugar: 1, sodium: 7, cat: 'Fats' },
  { id: 'f13', name: 'Sweet Potato, baked', brand: 'Generic', serving: '1 medium', calories: 103, protein: 2, carbs: 24, fat: 0, fiber: 4, sugar: 7, sodium: 41, cat: 'Vegetables' },
  { id: 'f14', name: 'Broccoli, steamed', brand: 'Generic', serving: '1 cup', calories: 55, protein: 4, carbs: 11, fat: 1, fiber: 5, sugar: 2, sodium: 64, cat: 'Vegetables' },
  { id: 'f15', name: 'Ground Turkey 93%', brand: 'Generic', serving: '4 oz', calories: 170, protein: 22, carbs: 0, fat: 9, fiber: 0, sugar: 0, sodium: 80, cat: 'Protein' },
  { id: 'f16', name: 'Olive Oil', brand: 'Generic', serving: '1 tbsp', calories: 119, protein: 0, carbs: 0, fat: 14, fiber: 0, sugar: 0, sodium: 0, cat: 'Fats' },
  { id: 'f17', name: 'Apple', brand: 'Generic', serving: '1 medium', calories: 95, protein: 0, carbs: 25, fat: 0, fiber: 4, sugar: 19, sodium: 2, cat: 'Fruit' },
  { id: 'f18', name: 'Cottage Cheese, 2%', brand: 'Generic', serving: '1 cup', calories: 183, protein: 24, carbs: 11, fat: 5, fiber: 0, sugar: 9, sodium: 746, cat: 'Protein' },
  { id: 'f19', name: 'Energy Bar', brand: 'CLIF', serving: '1 bar', calories: 250, protein: 9, carbs: 45, fat: 5, fiber: 5, sugar: 21, sodium: 150, cat: 'Snacks' },
  { id: 'f20', name: 'Sports Drink', brand: 'Gatorade', serving: '20 fl oz', calories: 140, protein: 0, carbs: 36, fat: 0, fiber: 0, sugar: 34, sodium: 270, cat: 'Drinks' },
  { id: 'f21', name: 'Black Coffee', brand: 'Generic', serving: '12 fl oz', calories: 2, protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, sodium: 5, cat: 'Drinks' },
  { id: 'f22', name: 'Quinoa, cooked', brand: 'Generic', serving: '1 cup', calories: 222, protein: 8, carbs: 39, fat: 4, fiber: 5, sugar: 2, sodium: 13, cat: 'Grains' },
  { id: 'f23', name: 'Spinach, raw', brand: 'Generic', serving: '2 cups', calories: 14, protein: 2, carbs: 2, fat: 0, fiber: 1, sugar: 0, sodium: 48, cat: 'Vegetables' },
  { id: 'f24', name: 'Blueberries', brand: 'Generic', serving: '1 cup', calories: 84, protein: 1, carbs: 21, fat: 0, fiber: 4, sugar: 15, sodium: 1, cat: 'Fruit' },
  { id: 'f25', name: 'Pasta, cooked', brand: 'Generic', serving: '1 cup', calories: 220, protein: 8, carbs: 43, fat: 1, fiber: 3, sugar: 1, sodium: 1, cat: 'Grains' },
  { id: 'f26', name: 'Whole Wheat Pasta, cooked', brand: 'Generic', serving: '1 cup', calories: 174, protein: 7, carbs: 37, fat: 1, fiber: 6, sugar: 1, sodium: 4, cat: 'Grains' },
  { id: 'f27', name: 'Spaghetti with Marinara', brand: 'Generic', serving: '1.5 cups', calories: 380, protein: 12, carbs: 68, fat: 7, fiber: 7, sugar: 12, sodium: 620, cat: 'Prepared' },
  { id: 'f28', name: 'Mac and Cheese', brand: 'Generic', serving: '1 cup', calories: 350, protein: 13, carbs: 44, fat: 14, fiber: 2, sugar: 6, sodium: 780, cat: 'Prepared' },
  { id: 'f29', name: 'Egg Noodles, cooked', brand: 'Generic', serving: '1 cup', calories: 221, protein: 7, carbs: 40, fat: 3, fiber: 2, sugar: 1, sodium: 8, cat: 'Grains' },
  { id: 'f30', name: 'Ramen Noodles, prepared', brand: 'Generic', serving: '1 package', calories: 380, protein: 9, carbs: 54, fat: 14, fiber: 2, sugar: 1, sodium: 1590, cat: 'Prepared' },
  { id: 'f31', name: 'Rice Noodles, cooked', brand: 'Generic', serving: '1 cup', calories: 190, protein: 2, carbs: 42, fat: 0, fiber: 2, sugar: 0, sodium: 33, cat: 'Grains' },
  { id: 'f32', name: 'Couscous, cooked', brand: 'Generic', serving: '1 cup', calories: 176, protein: 6, carbs: 36, fat: 0, fiber: 2, sugar: 0, sodium: 8, cat: 'Grains' },
  { id: 'f33', name: 'Gnocchi, cooked', brand: 'Generic', serving: '1 cup', calories: 250, protein: 5, carbs: 55, fat: 1, fiber: 3, sugar: 1, sodium: 400, cat: 'Grains' },
  { id: 'f34', name: 'Lasagna with Meat', brand: 'Generic', serving: '1 piece', calories: 336, protein: 20, carbs: 35, fat: 13, fiber: 3, sugar: 8, sodium: 900, cat: 'Prepared' },
  { id: 'f35', name: 'White Rice, cooked', brand: 'Generic', serving: '1 cup', calories: 205, protein: 4, carbs: 45, fat: 0, fiber: 1, sugar: 0, sodium: 2, cat: 'Grains' },
  { id: 'f36', name: 'Jasmine Rice, cooked', brand: 'Generic', serving: '1 cup', calories: 210, protein: 4, carbs: 45, fat: 0, fiber: 1, sugar: 0, sodium: 5, cat: 'Grains' },
  { id: 'f37', name: 'Fried Rice', brand: 'Generic', serving: '1 cup', calories: 238, protein: 6, carbs: 34, fat: 8, fiber: 1, sugar: 1, sodium: 530, cat: 'Prepared' },
  { id: 'f38', name: 'Barley, cooked', brand: 'Generic', serving: '1 cup', calories: 193, protein: 4, carbs: 44, fat: 1, fiber: 6, sugar: 0, sodium: 5, cat: 'Grains' },
  { id: 'f39', name: 'Farro, cooked', brand: 'Generic', serving: '1 cup', calories: 200, protein: 7, carbs: 40, fat: 2, fiber: 5, sugar: 1, sodium: 10, cat: 'Grains' },
  { id: 'f40', name: 'Corn Tortilla', brand: 'Generic', serving: '2 tortillas', calories: 104, protein: 3, carbs: 21, fat: 1, fiber: 3, sugar: 0, sodium: 22, cat: 'Grains' },
  { id: 'f41', name: 'Flour Tortilla', brand: 'Generic', serving: '1 large', calories: 210, protein: 6, carbs: 36, fat: 5, fiber: 2, sugar: 1, sodium: 480, cat: 'Grains' },
  { id: 'f42', name: 'Bagel, plain', brand: 'Generic', serving: '1 bagel', calories: 289, protein: 11, carbs: 56, fat: 2, fiber: 2, sugar: 6, sodium: 561, cat: 'Breakfast' },
  { id: 'f43', name: 'English Muffin', brand: 'Generic', serving: '1 muffin', calories: 134, protein: 4, carbs: 26, fat: 1, fiber: 2, sugar: 2, sodium: 264, cat: 'Breakfast' },
  { id: 'f44', name: 'Sourdough Bread', brand: 'Generic', serving: '2 slices', calories: 188, protein: 8, carbs: 36, fat: 1, fiber: 2, sugar: 2, sodium: 420, cat: 'Grains' },
  { id: 'f45', name: 'White Bread', brand: 'Generic', serving: '2 slices', calories: 150, protein: 4, carbs: 28, fat: 2, fiber: 1, sugar: 3, sodium: 280, cat: 'Grains' },
  { id: 'f46', name: 'Pita Bread', brand: 'Generic', serving: '1 pita', calories: 165, protein: 5, carbs: 33, fat: 1, fiber: 1, sugar: 1, sodium: 322, cat: 'Grains' },
  { id: 'f47', name: 'Naan', brand: 'Generic', serving: '1 piece', calories: 262, protein: 9, carbs: 45, fat: 5, fiber: 2, sugar: 3, sodium: 418, cat: 'Grains' },
  { id: 'f48', name: 'Dinner Roll', brand: 'Generic', serving: '1 roll', calories: 87, protein: 3, carbs: 15, fat: 2, fiber: 1, sugar: 2, sodium: 150, cat: 'Grains' },
  { id: 'f49', name: 'Croissant', brand: 'Generic', serving: '1 medium', calories: 231, protein: 5, carbs: 26, fat: 12, fiber: 1, sugar: 6, sodium: 424, cat: 'Breakfast' },
  { id: 'f50', name: 'Cheerios', brand: 'Generic', serving: '1.5 cups', calories: 140, protein: 5, carbs: 29, fat: 3, fiber: 4, sugar: 2, sodium: 190, cat: 'Breakfast' },
  { id: 'f51', name: 'Granola', brand: 'Generic', serving: '1/2 cup', calories: 240, protein: 6, carbs: 32, fat: 10, fiber: 4, sugar: 12, sodium: 25, cat: 'Breakfast' },
  { id: 'f52', name: 'Pancakes', brand: 'Generic', serving: '2 medium', calories: 175, protein: 5, carbs: 22, fat: 7, fiber: 1, sugar: 5, sodium: 440, cat: 'Breakfast' },
  { id: 'f53', name: 'Waffle', brand: 'Generic', serving: '1 waffle', calories: 218, protein: 6, carbs: 25, fat: 11, fiber: 1, sugar: 4, sodium: 383, cat: 'Breakfast' },
  { id: 'f54', name: 'French Toast', brand: 'Generic', serving: '2 slices', calories: 300, protein: 10, carbs: 32, fat: 14, fiber: 2, sugar: 8, sodium: 450, cat: 'Breakfast' },
  { id: 'f55', name: 'Hash Browns', brand: 'Generic', serving: '1 cup', calories: 210, protein: 2, carbs: 27, fat: 11, fiber: 2, sugar: 0, sodium: 320, cat: 'Breakfast' },
  { id: 'f56', name: 'Breakfast Burrito', brand: 'Generic', serving: '1 burrito', calories: 400, protein: 18, carbs: 38, fat: 19, fiber: 3, sugar: 2, sodium: 900, cat: 'Prepared' },
  { id: 'f57', name: 'Overnight Oats', brand: 'Generic', serving: '1 jar', calories: 320, protein: 12, carbs: 50, fat: 8, fiber: 7, sugar: 14, sodium: 105, cat: 'Breakfast' },
  { id: 'f58', name: 'Whole Milk', brand: 'Generic', serving: '1 cup', calories: 149, protein: 8, carbs: 12, fat: 8, fiber: 0, sugar: 12, sodium: 105, cat: 'Dairy' },
  { id: 'f59', name: '2% Milk', brand: 'Generic', serving: '1 cup', calories: 122, protein: 8, carbs: 12, fat: 5, fiber: 0, sugar: 12, sodium: 100, cat: 'Dairy' },
  { id: 'f60', name: 'Skim Milk', brand: 'Generic', serving: '1 cup', calories: 83, protein: 8, carbs: 12, fat: 0, fiber: 0, sugar: 12, sodium: 103, cat: 'Dairy' },
  { id: 'f61', name: 'Almond Milk, unsweetened', brand: 'Generic', serving: '1 cup', calories: 37, protein: 1, carbs: 3, fat: 3, fiber: 1, sugar: 2, sodium: 176, cat: 'Dairy' },
  { id: 'f62', name: 'Oat Milk', brand: 'Generic', serving: '1 cup', calories: 120, protein: 3, carbs: 16, fat: 5, fiber: 2, sugar: 7, sodium: 100, cat: 'Dairy' },
  { id: 'f63', name: 'Cheddar Cheese', brand: 'Generic', serving: '1 oz', calories: 114, protein: 7, carbs: 1, fat: 9, fiber: 0, sugar: 0, sodium: 180, cat: 'Dairy' },
  { id: 'f64', name: 'Mozzarella, part skim', brand: 'Generic', serving: '1 oz', calories: 72, protein: 7, carbs: 1, fat: 5, fiber: 0, sugar: 0, sodium: 175, cat: 'Dairy' },
  { id: 'f65', name: 'Parmesan, grated', brand: 'Generic', serving: '2 tbsp', calories: 42, protein: 4, carbs: 0, fat: 3, fiber: 0, sugar: 0, sodium: 170, cat: 'Dairy' },
  { id: 'f66', name: 'Swiss Cheese', brand: 'Generic', serving: '1 slice', calories: 106, protein: 8, carbs: 2, fat: 8, fiber: 0, sugar: 0, sodium: 54, cat: 'Dairy' },
  { id: 'f67', name: 'Cream Cheese', brand: 'Generic', serving: '2 tbsp', calories: 100, protein: 2, carbs: 2, fat: 10, fiber: 0, sugar: 1, sodium: 105, cat: 'Dairy' },
  { id: 'f68', name: 'Feta Cheese', brand: 'Generic', serving: '1/4 cup', calories: 99, protein: 5, carbs: 2, fat: 8, fiber: 0, sugar: 0, sodium: 425, cat: 'Dairy' },
  { id: 'f69', name: 'String Cheese', brand: 'Generic', serving: '1 stick', calories: 80, protein: 7, carbs: 1, fat: 6, fiber: 0, sugar: 0, sodium: 200, cat: 'Dairy' },
  { id: 'f70', name: 'Butter', brand: 'Generic', serving: '1 tbsp', calories: 102, protein: 0, carbs: 0, fat: 12, fiber: 0, sugar: 0, sodium: 91, cat: 'Fats' },
  { id: 'f71', name: 'Heavy Cream', brand: 'Generic', serving: '2 tbsp', calories: 101, protein: 1, carbs: 1, fat: 11, fiber: 0, sugar: 1, sodium: 8, cat: 'Dairy' },
  { id: 'f72', name: 'Sour Cream', brand: 'Generic', serving: '2 tbsp', calories: 46, protein: 1, carbs: 1, fat: 4, fiber: 0, sugar: 1, sodium: 10, cat: 'Dairy' },
  { id: 'f73', name: 'Vanilla Ice Cream', brand: 'Generic', serving: '2/3 cup', calories: 274, protein: 5, carbs: 31, fat: 15, fiber: 1, sugar: 28, sodium: 106, cat: 'Snacks' },
  { id: 'f74', name: 'Greek Yogurt, whole milk', brand: 'Generic', serving: '1 cup', calories: 220, protein: 20, carbs: 9, fat: 11, fiber: 0, sugar: 9, sodium: 80, cat: 'Breakfast' },
  { id: 'f75', name: 'Egg Whites', brand: 'Generic', serving: '1/2 cup', calories: 63, protein: 13, carbs: 1, fat: 0, fiber: 0, sugar: 1, sodium: 200, cat: 'Protein' },
  { id: 'f76', name: 'Scrambled Eggs', brand: 'Generic', serving: '2 eggs', calories: 182, protein: 12, carbs: 2, fat: 13, fiber: 0, sugar: 2, sodium: 342, cat: 'Breakfast' },
  { id: 'f77', name: 'Hard-Boiled Egg', brand: 'Generic', serving: '1 egg', calories: 78, protein: 6, carbs: 1, fat: 5, fiber: 0, sugar: 1, sodium: 62, cat: 'Protein' },
  { id: 'f78', name: 'Ground Beef 90%, cooked', brand: 'Generic', serving: '4 oz', calories: 230, protein: 26, carbs: 0, fat: 13, fiber: 0, sugar: 0, sodium: 82, cat: 'Protein' },
  { id: 'f79', name: 'Ground Beef 80%, cooked', brand: 'Generic', serving: '4 oz', calories: 305, protein: 25, carbs: 0, fat: 22, fiber: 0, sugar: 0, sodium: 87, cat: 'Protein' },
  { id: 'f80', name: 'Ribeye Steak', brand: 'Generic', serving: '6 oz', calories: 466, protein: 40, carbs: 0, fat: 33, fiber: 0, sugar: 0, sodium: 108, cat: 'Protein' },
  { id: 'f81', name: 'Sirloin Steak', brand: 'Generic', serving: '6 oz', calories: 344, protein: 52, carbs: 0, fat: 14, fiber: 0, sugar: 0, sodium: 120, cat: 'Protein' },
  { id: 'f82', name: 'Pork Chop, boneless', brand: 'Generic', serving: '5 oz', calories: 290, protein: 39, carbs: 0, fat: 14, fiber: 0, sugar: 0, sodium: 90, cat: 'Protein' },
  { id: 'f83', name: 'Pork Tenderloin', brand: 'Generic', serving: '4 oz', calories: 158, protein: 30, carbs: 0, fat: 4, fiber: 0, sugar: 0, sodium: 63, cat: 'Protein' },
  { id: 'f84', name: 'Bacon', brand: 'Generic', serving: '3 slices', calories: 130, protein: 9, carbs: 0, fat: 10, fiber: 0, sugar: 0, sodium: 435, cat: 'Protein' },
  { id: 'f85', name: 'Ham, sliced', brand: 'Generic', serving: '3 oz', calories: 100, protein: 15, carbs: 2, fat: 3, fiber: 0, sugar: 1, sodium: 1050, cat: 'Protein' },
  { id: 'f86', name: 'Italian Sausage', brand: 'Generic', serving: '1 link', calories: 234, protein: 13, carbs: 3, fat: 19, fiber: 0, sugar: 1, sodium: 618, cat: 'Protein' },
  { id: 'f87', name: 'Pepperoni', brand: 'Generic', serving: '14 slices', calories: 135, protein: 6, carbs: 0, fat: 12, fiber: 0, sugar: 0, sodium: 470, cat: 'Protein' },
  { id: 'f88', name: 'Chicken Thigh, roasted', brand: 'Generic', serving: '1 thigh', calories: 208, protein: 26, carbs: 0, fat: 11, fiber: 0, sugar: 0, sodium: 90, cat: 'Protein' },
  { id: 'f89', name: 'Chicken Drumstick', brand: 'Generic', serving: '1 drumstick', calories: 172, protein: 22, carbs: 0, fat: 9, fiber: 0, sugar: 0, sodium: 84, cat: 'Protein' },
  { id: 'f90', name: 'Ground Chicken, cooked', brand: 'Generic', serving: '4 oz', calories: 190, protein: 23, carbs: 0, fat: 11, fiber: 0, sugar: 0, sodium: 85, cat: 'Protein' },
  { id: 'f91', name: 'Rotisserie Chicken, mixed', brand: 'Generic', serving: '4 oz', calories: 210, protein: 27, carbs: 0, fat: 11, fiber: 0, sugar: 0, sodium: 380, cat: 'Protein' },
  { id: 'f92', name: 'Chicken Wings', brand: 'Generic', serving: '4 wings', calories: 340, protein: 30, carbs: 0, fat: 24, fiber: 0, sugar: 0, sodium: 260, cat: 'Protein' },
  { id: 'f93', name: 'Grilled Chicken Sandwich', brand: 'Generic', serving: '1 sandwich', calories: 420, protein: 34, carbs: 42, fat: 12, fiber: 3, sugar: 7, sodium: 950, cat: 'Prepared' },
  { id: 'f94', name: 'Turkey Breast, deli', brand: 'Generic', serving: '3 oz', calories: 90, protein: 18, carbs: 2, fat: 1, fiber: 0, sugar: 1, sodium: 780, cat: 'Protein' },
  { id: 'f95', name: 'Steak Burrito', brand: 'Generic', serving: '1 burrito', calories: 690, protein: 40, carbs: 78, fat: 24, fiber: 8, sugar: 4, sodium: 1600, cat: 'Prepared' },
  { id: 'f96', name: 'Tuna, canned in water', brand: 'Generic', serving: '1 can', calories: 120, protein: 27, carbs: 0, fat: 1, fiber: 0, sugar: 0, sodium: 320, cat: 'Protein' },
  { id: 'f97', name: 'Shrimp, cooked', brand: 'Generic', serving: '4 oz', calories: 112, protein: 24, carbs: 0, fat: 1, fiber: 0, sugar: 0, sodium: 422, cat: 'Protein' },
  { id: 'f98', name: 'Tilapia, baked', brand: 'Generic', serving: '6 oz', calories: 218, protein: 45, carbs: 0, fat: 4, fiber: 0, sugar: 0, sodium: 94, cat: 'Protein' },
  { id: 'f99', name: 'Cod, baked', brand: 'Generic', serving: '6 oz', calories: 178, protein: 39, carbs: 0, fat: 1, fiber: 0, sugar: 0, sodium: 132, cat: 'Protein' },
  { id: 'f100', name: 'Sardines in Olive Oil', brand: 'Generic', serving: '1 can', calories: 191, protein: 22, carbs: 0, fat: 11, fiber: 0, sugar: 0, sodium: 465, cat: 'Protein' },
  { id: 'f101', name: 'Smoked Salmon', brand: 'Generic', serving: '3 oz', calories: 100, protein: 16, carbs: 0, fat: 4, fiber: 0, sugar: 0, sodium: 570, cat: 'Protein' },
  { id: 'f102', name: 'Crab Meat', brand: 'Generic', serving: '4 oz', calories: 98, protein: 21, carbs: 0, fat: 1, fiber: 0, sugar: 0, sodium: 380, cat: 'Protein' },
  { id: 'f103', name: 'Fish Sticks', brand: 'Generic', serving: '5 sticks', calories: 250, protein: 11, carbs: 22, fat: 13, fiber: 1, sugar: 2, sodium: 400, cat: 'Prepared' },
  { id: 'f104', name: 'California Roll', brand: 'Generic', serving: '8 pieces', calories: 255, protein: 9, carbs: 38, fat: 7, fiber: 3, sugar: 6, sodium: 430, cat: 'Prepared' },
  { id: 'f105', name: 'Black Beans, cooked', brand: 'Generic', serving: '1 cup', calories: 227, protein: 15, carbs: 41, fat: 1, fiber: 15, sugar: 0, sodium: 2, cat: 'Legumes' },
  { id: 'f106', name: 'Chickpeas, cooked', brand: 'Generic', serving: '1 cup', calories: 269, protein: 15, carbs: 45, fat: 4, fiber: 13, sugar: 8, sodium: 11, cat: 'Legumes' },
  { id: 'f107', name: 'Lentils, cooked', brand: 'Generic', serving: '1 cup', calories: 230, protein: 18, carbs: 40, fat: 1, fiber: 16, sugar: 4, sodium: 4, cat: 'Legumes' },
  { id: 'f108', name: 'Kidney Beans, cooked', brand: 'Generic', serving: '1 cup', calories: 225, protein: 15, carbs: 40, fat: 1, fiber: 13, sugar: 1, sodium: 2, cat: 'Legumes' },
  { id: 'f109', name: 'Pinto Beans, cooked', brand: 'Generic', serving: '1 cup', calories: 245, protein: 15, carbs: 45, fat: 1, fiber: 15, sugar: 1, sodium: 2, cat: 'Legumes' },
  { id: 'f110', name: 'Refried Beans', brand: 'Generic', serving: '1/2 cup', calories: 110, protein: 6, carbs: 18, fat: 2, fiber: 6, sugar: 1, sodium: 490, cat: 'Legumes' },
  { id: 'f111', name: 'Edamame, shelled', brand: 'Generic', serving: '1 cup', calories: 188, protein: 18, carbs: 14, fat: 8, fiber: 8, sugar: 3, sodium: 9, cat: 'Legumes' },
  { id: 'f112', name: 'Tofu, firm', brand: 'Generic', serving: '1/2 block', calories: 181, protein: 20, carbs: 4, fat: 11, fiber: 2, sugar: 1, sodium: 18, cat: 'Protein' },
  { id: 'f113', name: 'Tempeh', brand: 'Generic', serving: '4 oz', calories: 220, protein: 21, carbs: 9, fat: 13, fiber: 5, sugar: 0, sodium: 10, cat: 'Protein' },
  { id: 'f114', name: 'Hummus', brand: 'Generic', serving: '1/4 cup', calories: 105, protein: 5, carbs: 9, fat: 6, fiber: 4, sugar: 0, sodium: 240, cat: 'Legumes' },
  { id: 'f115', name: 'Falafel', brand: 'Generic', serving: '4 patties', calories: 228, protein: 9, carbs: 22, fat: 12, fiber: 5, sugar: 1, sodium: 585, cat: 'Prepared' },
  { id: 'f116', name: 'Carrots, raw', brand: 'Generic', serving: '1 cup', calories: 52, protein: 1, carbs: 12, fat: 0, fiber: 4, sugar: 6, sodium: 88, cat: 'Vegetables' },
  { id: 'f117', name: 'Bell Pepper', brand: 'Generic', serving: '1 medium', calories: 25, protein: 1, carbs: 6, fat: 0, fiber: 2, sugar: 4, sodium: 4, cat: 'Vegetables' },
  { id: 'f118', name: 'Cucumber', brand: 'Generic', serving: '1 cup', calories: 16, protein: 1, carbs: 4, fat: 0, fiber: 1, sugar: 2, sodium: 2, cat: 'Vegetables' },
  { id: 'f119', name: 'Tomato', brand: 'Generic', serving: '1 medium', calories: 22, protein: 1, carbs: 5, fat: 0, fiber: 2, sugar: 3, sodium: 6, cat: 'Vegetables' },
  { id: 'f120', name: 'Cherry Tomatoes', brand: 'Generic', serving: '1 cup', calories: 27, protein: 1, carbs: 6, fat: 0, fiber: 2, sugar: 4, sodium: 7, cat: 'Vegetables' },
  { id: 'f121', name: 'Onion', brand: 'Generic', serving: '1 medium', calories: 44, protein: 1, carbs: 10, fat: 0, fiber: 2, sugar: 5, sodium: 4, cat: 'Vegetables' },
  { id: 'f122', name: 'Garlic', brand: 'Generic', serving: '3 cloves', calories: 13, protein: 1, carbs: 3, fat: 0, fiber: 0, sugar: 0, sodium: 2, cat: 'Vegetables' },
  { id: 'f123', name: 'Mushrooms, sautéed', brand: 'Generic', serving: '1 cup', calories: 44, protein: 3, carbs: 6, fat: 2, fiber: 2, sugar: 3, sodium: 10, cat: 'Vegetables' },
  { id: 'f124', name: 'Zucchini, cooked', brand: 'Generic', serving: '1 cup', calories: 27, protein: 2, carbs: 5, fat: 0, fiber: 2, sugar: 4, sodium: 5, cat: 'Vegetables' },
  { id: 'f125', name: 'Cauliflower, roasted', brand: 'Generic', serving: '1 cup', calories: 40, protein: 2, carbs: 6, fat: 2, fiber: 3, sugar: 3, sodium: 20, cat: 'Vegetables' },
  { id: 'f126', name: 'Brussels Sprouts, roasted', brand: 'Generic', serving: '1 cup', calories: 80, protein: 4, carbs: 11, fat: 4, fiber: 4, sugar: 3, sodium: 25, cat: 'Vegetables' },
  { id: 'f127', name: 'Kale, cooked', brand: 'Generic', serving: '1 cup', calories: 36, protein: 2, carbs: 7, fat: 1, fiber: 3, sugar: 2, sodium: 30, cat: 'Vegetables' },
  { id: 'f128', name: 'Asparagus, cooked', brand: 'Generic', serving: '1 cup', calories: 40, protein: 4, carbs: 7, fat: 0, fiber: 4, sugar: 2, sodium: 25, cat: 'Vegetables' },
  { id: 'f129', name: 'Green Beans, cooked', brand: 'Generic', serving: '1 cup', calories: 44, protein: 2, carbs: 10, fat: 0, fiber: 4, sugar: 2, sodium: 1, cat: 'Vegetables' },
  { id: 'f130', name: 'Corn, sweet', brand: 'Generic', serving: '1 ear', calories: 88, protein: 3, carbs: 19, fat: 1, fiber: 2, sugar: 6, sodium: 15, cat: 'Vegetables' },
  { id: 'f131', name: 'Peas, cooked', brand: 'Generic', serving: '1 cup', calories: 134, protein: 9, carbs: 25, fat: 0, fiber: 9, sugar: 9, sodium: 5, cat: 'Vegetables' },
  { id: 'f132', name: 'Potato, baked', brand: 'Generic', serving: '1 medium', calories: 161, protein: 4, carbs: 37, fat: 0, fiber: 4, sugar: 2, sodium: 17, cat: 'Vegetables' },
  { id: 'f133', name: 'Mashed Potatoes', brand: 'Generic', serving: '1 cup', calories: 214, protein: 4, carbs: 35, fat: 7, fiber: 3, sugar: 3, sodium: 620, cat: 'Prepared' },
  { id: 'f134', name: 'French Fries', brand: 'Generic', serving: '1 medium order', calories: 365, protein: 4, carbs: 48, fat: 17, fiber: 4, sugar: 0, sodium: 246, cat: 'Prepared' },
  { id: 'f135', name: 'Celery', brand: 'Generic', serving: '2 stalks', calories: 13, protein: 1, carbs: 3, fat: 0, fiber: 1, sugar: 1, sodium: 64, cat: 'Vegetables' },
  { id: 'f136', name: 'Lettuce, romaine', brand: 'Generic', serving: '2 cups', calories: 16, protein: 1, carbs: 3, fat: 0, fiber: 2, sugar: 1, sodium: 8, cat: 'Vegetables' },
  { id: 'f137', name: 'Mixed Salad Greens', brand: 'Generic', serving: '2 cups', calories: 18, protein: 2, carbs: 3, fat: 0, fiber: 2, sugar: 1, sodium: 20, cat: 'Vegetables' },
  { id: 'f138', name: 'Coleslaw', brand: 'Generic', serving: '1/2 cup', calories: 150, protein: 1, carbs: 13, fat: 11, fiber: 2, sugar: 10, sodium: 190, cat: 'Prepared' },
  { id: 'f139', name: 'Butternut Squash, roasted', brand: 'Generic', serving: '1 cup', calories: 82, protein: 2, carbs: 22, fat: 0, fiber: 7, sugar: 4, sodium: 8, cat: 'Vegetables' },
  { id: 'f140', name: 'Orange', brand: 'Generic', serving: '1 medium', calories: 62, protein: 1, carbs: 15, fat: 0, fiber: 3, sugar: 12, sodium: 0, cat: 'Fruit' },
  { id: 'f141', name: 'Strawberries', brand: 'Generic', serving: '1 cup', calories: 49, protein: 1, carbs: 12, fat: 0, fiber: 3, sugar: 7, sodium: 2, cat: 'Fruit' },
  { id: 'f142', name: 'Grapes', brand: 'Generic', serving: '1 cup', calories: 104, protein: 1, carbs: 27, fat: 0, fiber: 1, sugar: 23, sodium: 3, cat: 'Fruit' },
  { id: 'f143', name: 'Watermelon', brand: 'Generic', serving: '1 cup', calories: 46, protein: 1, carbs: 12, fat: 0, fiber: 1, sugar: 9, sodium: 2, cat: 'Fruit' },
  { id: 'f144', name: 'Pineapple', brand: 'Generic', serving: '1 cup', calories: 82, protein: 1, carbs: 22, fat: 0, fiber: 2, sugar: 16, sodium: 2, cat: 'Fruit' },
  { id: 'f145', name: 'Mango', brand: 'Generic', serving: '1 cup', calories: 99, protein: 1, carbs: 25, fat: 1, fiber: 3, sugar: 23, sodium: 2, cat: 'Fruit' },
  { id: 'f146', name: 'Peach', brand: 'Generic', serving: '1 medium', calories: 59, protein: 1, carbs: 14, fat: 0, fiber: 2, sugar: 13, sodium: 0, cat: 'Fruit' },
  { id: 'f147', name: 'Pear', brand: 'Generic', serving: '1 medium', calories: 101, protein: 1, carbs: 27, fat: 0, fiber: 6, sugar: 17, sodium: 2, cat: 'Fruit' },
  { id: 'f148', name: 'Raspberries', brand: 'Generic', serving: '1 cup', calories: 64, protein: 1, carbs: 15, fat: 1, fiber: 8, sugar: 5, sodium: 1, cat: 'Fruit' },
  { id: 'f149', name: 'Blackberries', brand: 'Generic', serving: '1 cup', calories: 62, protein: 2, carbs: 14, fat: 1, fiber: 8, sugar: 7, sodium: 1, cat: 'Fruit' },
  { id: 'f150', name: 'Cherries', brand: 'Generic', serving: '1 cup', calories: 97, protein: 2, carbs: 25, fat: 0, fiber: 3, sugar: 20, sodium: 0, cat: 'Fruit' },
  { id: 'f151', name: 'Kiwi', brand: 'Generic', serving: '2 fruits', calories: 84, protein: 2, carbs: 20, fat: 1, fiber: 4, sugar: 12, sodium: 4, cat: 'Fruit' },
  { id: 'f152', name: 'Raisins', brand: 'Generic', serving: '1/4 cup', calories: 108, protein: 1, carbs: 29, fat: 0, fiber: 1, sugar: 21, sodium: 4, cat: 'Fruit' },
  { id: 'f153', name: 'Dates, Medjool', brand: 'Generic', serving: '2 dates', calories: 133, protein: 1, carbs: 36, fat: 0, fiber: 3, sugar: 32, sodium: 0, cat: 'Fruit' },
  { id: 'f154', name: 'Applesauce, unsweetened', brand: 'Generic', serving: '1/2 cup', calories: 51, protein: 0, carbs: 14, fat: 0, fiber: 1, sugar: 11, sodium: 2, cat: 'Fruit' },
  { id: 'f155', name: 'Walnuts', brand: 'Generic', serving: '1 oz', calories: 185, protein: 4, carbs: 4, fat: 18, fiber: 2, sugar: 1, sodium: 1, cat: 'Snacks' },
  { id: 'f156', name: 'Cashews', brand: 'Generic', serving: '1 oz', calories: 157, protein: 5, carbs: 9, fat: 12, fiber: 1, sugar: 2, sodium: 3, cat: 'Snacks' },
  { id: 'f157', name: 'Pistachios', brand: 'Generic', serving: '1 oz', calories: 159, protein: 6, carbs: 8, fat: 13, fiber: 3, sugar: 2, sodium: 0, cat: 'Snacks' },
  { id: 'f158', name: 'Pecans', brand: 'Generic', serving: '1 oz', calories: 196, protein: 3, carbs: 4, fat: 20, fiber: 3, sugar: 1, sodium: 0, cat: 'Snacks' },
  { id: 'f159', name: 'Almond Butter', brand: 'Generic', serving: '2 tbsp', calories: 196, protein: 7, carbs: 6, fat: 18, fiber: 3, sugar: 2, sodium: 2, cat: 'Fats' },
  { id: 'f160', name: 'Chia Seeds', brand: 'Generic', serving: '2 tbsp', calories: 138, protein: 5, carbs: 12, fat: 9, fiber: 10, sugar: 0, sodium: 5, cat: 'Fats' },
  { id: 'f161', name: 'Flaxseed, ground', brand: 'Generic', serving: '2 tbsp', calories: 74, protein: 3, carbs: 4, fat: 6, fiber: 4, sugar: 0, sodium: 4, cat: 'Fats' },
  { id: 'f162', name: 'Pumpkin Seeds', brand: 'Generic', serving: '1 oz', calories: 158, protein: 9, carbs: 3, fat: 14, fiber: 2, sugar: 0, sodium: 2, cat: 'Snacks' },
  { id: 'f163', name: 'Sunflower Seeds', brand: 'Generic', serving: '1 oz', calories: 165, protein: 6, carbs: 6, fat: 14, fiber: 3, sugar: 1, sodium: 1, cat: 'Snacks' },
  { id: 'f164', name: 'Trail Mix', brand: 'Generic', serving: '1/4 cup', calories: 173, protein: 5, carbs: 17, fat: 11, fiber: 2, sugar: 10, sodium: 60, cat: 'Snacks' },
  { id: 'f165', name: 'Coconut Oil', brand: 'Generic', serving: '1 tbsp', calories: 121, protein: 0, carbs: 0, fat: 13, fiber: 0, sugar: 0, sodium: 0, cat: 'Fats' },
  { id: 'f166', name: 'Mayonnaise', brand: 'Generic', serving: '1 tbsp', calories: 94, protein: 0, carbs: 0, fat: 10, fiber: 0, sugar: 0, sodium: 88, cat: 'Fats' },
  { id: 'f167', name: 'Ranch Dressing', brand: 'Generic', serving: '2 tbsp', calories: 129, protein: 0, carbs: 2, fat: 13, fiber: 0, sugar: 1, sodium: 270, cat: 'Fats' },
  { id: 'f168', name: 'Caesar Dressing', brand: 'Generic', serving: '2 tbsp', calories: 163, protein: 1, carbs: 1, fat: 17, fiber: 0, sugar: 1, sodium: 323, cat: 'Fats' },
  { id: 'f169', name: 'Balsamic Vinaigrette', brand: 'Generic', serving: '2 tbsp', calories: 88, protein: 0, carbs: 3, fat: 8, fiber: 0, sugar: 2, sodium: 190, cat: 'Fats' },
  { id: 'f170', name: 'Ketchup', brand: 'Generic', serving: '1 tbsp', calories: 17, protein: 0, carbs: 5, fat: 0, fiber: 0, sugar: 4, sodium: 154, cat: 'Condiments' },
  { id: 'f171', name: 'Mustard', brand: 'Generic', serving: '1 tbsp', calories: 9, protein: 1, carbs: 1, fat: 0, fiber: 0, sugar: 0, sodium: 165, cat: 'Condiments' },
  { id: 'f172', name: 'Soy Sauce', brand: 'Generic', serving: '1 tbsp', calories: 8, protein: 1, carbs: 1, fat: 0, fiber: 0, sugar: 0, sodium: 879, cat: 'Condiments' },
  { id: 'f173', name: 'Sriracha', brand: 'Generic', serving: '1 tbsp', calories: 15, protein: 0, carbs: 3, fat: 0, fiber: 0, sugar: 2, sodium: 320, cat: 'Condiments' },
  { id: 'f174', name: 'Marinara Sauce', brand: 'Generic', serving: '1/2 cup', calories: 66, protein: 2, carbs: 10, fat: 2, fiber: 2, sugar: 6, sodium: 480, cat: 'Condiments' },
  { id: 'f175', name: 'Alfredo Sauce', brand: 'Generic', serving: '1/4 cup', calories: 110, protein: 2, carbs: 3, fat: 10, fiber: 0, sugar: 1, sodium: 400, cat: 'Condiments' },
  { id: 'f176', name: 'Pesto', brand: 'Generic', serving: '2 tbsp', calories: 160, protein: 3, carbs: 2, fat: 15, fiber: 1, sugar: 0, sodium: 240, cat: 'Condiments' },
  { id: 'f177', name: 'Salsa', brand: 'Generic', serving: '1/4 cup', calories: 18, protein: 1, carbs: 4, fat: 0, fiber: 1, sugar: 2, sodium: 260, cat: 'Condiments' },
  { id: 'f178', name: 'Guacamole', brand: 'Generic', serving: '1/4 cup', calories: 92, protein: 1, carbs: 5, fat: 8, fiber: 4, sugar: 0, sodium: 170, cat: 'Condiments' },
  { id: 'f179', name: 'Honey', brand: 'Generic', serving: '1 tbsp', calories: 64, protein: 0, carbs: 17, fat: 0, fiber: 0, sugar: 17, sodium: 1, cat: 'Condiments' },
  { id: 'f180', name: 'Maple Syrup', brand: 'Generic', serving: '2 tbsp', calories: 104, protein: 0, carbs: 27, fat: 0, fiber: 0, sugar: 24, sodium: 2, cat: 'Condiments' },
  { id: 'f181', name: 'Strawberry Jam', brand: 'Generic', serving: '1 tbsp', calories: 56, protein: 0, carbs: 14, fat: 0, fiber: 0, sugar: 10, sodium: 6, cat: 'Condiments' },
  { id: 'f182', name: 'BBQ Sauce', brand: 'Generic', serving: '2 tbsp', calories: 58, protein: 0, carbs: 14, fat: 0, fiber: 0, sugar: 12, sodium: 350, cat: 'Condiments' },
  { id: 'f183', name: 'Potato Chips', brand: 'Generic', serving: '1 oz', calories: 152, protein: 2, carbs: 15, fat: 10, fiber: 1, sugar: 0, sodium: 149, cat: 'Snacks' },
  { id: 'f184', name: 'Tortilla Chips', brand: 'Generic', serving: '1 oz', calories: 138, protein: 2, carbs: 19, fat: 6, fiber: 1, sugar: 0, sodium: 119, cat: 'Snacks' },
  { id: 'f185', name: 'Pretzels', brand: 'Generic', serving: '1 oz', calories: 108, protein: 3, carbs: 23, fat: 1, fiber: 1, sugar: 1, sodium: 385, cat: 'Snacks' },
  { id: 'f186', name: 'Popcorn, air-popped', brand: 'Generic', serving: '3 cups', calories: 93, protein: 3, carbs: 19, fat: 1, fiber: 4, sugar: 0, sodium: 2, cat: 'Snacks' },
  { id: 'f187', name: 'Crackers, whole wheat', brand: 'Generic', serving: '6 crackers', calories: 120, protein: 2, carbs: 18, fat: 5, fiber: 2, sugar: 3, sodium: 180, cat: 'Snacks' },
  { id: 'f188', name: 'Dark Chocolate 70%', brand: 'Generic', serving: '1 oz', calories: 170, protein: 2, carbs: 13, fat: 12, fiber: 3, sugar: 7, sodium: 6, cat: 'Snacks' },
  { id: 'f189', name: 'Chocolate Chip Cookie', brand: 'Generic', serving: '1 large', calories: 220, protein: 2, carbs: 30, fat: 11, fiber: 1, sugar: 18, sodium: 150, cat: 'Snacks' },
  { id: 'f190', name: 'Brownie', brand: 'Generic', serving: '1 square', calories: 227, protein: 3, carbs: 36, fat: 9, fiber: 1, sugar: 21, sodium: 150, cat: 'Snacks' },
  { id: 'f191', name: 'Beef Jerky', brand: 'Generic', serving: '1 oz', calories: 116, protein: 9, carbs: 3, fat: 7, fiber: 0, sugar: 3, sodium: 506, cat: 'Snacks' },
  { id: 'f192', name: 'Granola Bar', brand: 'Generic', serving: '1 bar', calories: 120, protein: 2, carbs: 20, fat: 4, fiber: 1, sugar: 8, sodium: 80, cat: 'Snacks' },
  { id: 'f193', name: 'Rice Cakes', brand: 'Generic', serving: '2 cakes', calories: 70, protein: 1, carbs: 15, fat: 1, fiber: 0, sugar: 0, sodium: 30, cat: 'Snacks' },
  { id: 'f194', name: 'Fruit Snacks', brand: 'Generic', serving: '1 pouch', calories: 80, protein: 0, carbs: 19, fat: 0, fiber: 0, sugar: 12, sodium: 25, cat: 'Snacks' },
  { id: 'f195', name: 'Orange Juice', brand: 'Generic', serving: '8 fl oz', calories: 112, protein: 2, carbs: 26, fat: 0, fiber: 0, sugar: 21, sodium: 2, cat: 'Drinks' },
  { id: 'f196', name: 'Apple Juice', brand: 'Generic', serving: '8 fl oz', calories: 114, protein: 0, carbs: 28, fat: 0, fiber: 0, sugar: 24, sodium: 10, cat: 'Drinks' },
  { id: 'f197', name: 'Cola', brand: 'Generic', serving: '12 fl oz', calories: 140, protein: 0, carbs: 39, fat: 0, fiber: 0, sugar: 39, sodium: 45, cat: 'Drinks' },
  { id: 'f198', name: 'Beer', brand: 'Generic', serving: '12 fl oz', calories: 153, protein: 2, carbs: 13, fat: 0, fiber: 0, sugar: 0, sodium: 14, cat: 'Drinks' },
  { id: 'f199', name: 'Light Beer', brand: 'Generic', serving: '12 fl oz', calories: 103, protein: 1, carbs: 6, fat: 0, fiber: 0, sugar: 0, sodium: 14, cat: 'Drinks' },
  { id: 'f200', name: 'Red Wine', brand: 'Generic', serving: '5 fl oz', calories: 125, protein: 0, carbs: 4, fat: 0, fiber: 0, sugar: 1, sodium: 6, cat: 'Drinks' },
  { id: 'f201', name: 'White Wine', brand: 'Generic', serving: '5 fl oz', calories: 121, protein: 0, carbs: 4, fat: 0, fiber: 0, sugar: 1, sodium: 7, cat: 'Drinks' },
  { id: 'f202', name: 'Fruit Smoothie', brand: 'Generic', serving: '16 fl oz', calories: 260, protein: 4, carbs: 60, fat: 2, fiber: 4, sugar: 48, sodium: 40, cat: 'Drinks' },
  { id: 'f203', name: 'Coconut Water', brand: 'Generic', serving: '11 fl oz', calories: 60, protein: 0, carbs: 15, fat: 0, fiber: 0, sugar: 11, sodium: 65, cat: 'Drinks' },
  { id: 'f204', name: 'Energy Drink', brand: 'Generic', serving: '8.4 fl oz', calories: 110, protein: 1, carbs: 28, fat: 0, fiber: 0, sugar: 27, sodium: 105, cat: 'Drinks' },
  { id: 'f205', name: 'Latte with 2% Milk', brand: 'Generic', serving: '16 fl oz', calories: 190, protein: 13, carbs: 19, fat: 7, fiber: 0, sugar: 18, sodium: 170, cat: 'Drinks' },
  { id: 'f206', name: 'Hot Chocolate', brand: 'Generic', serving: '12 fl oz', calories: 320, protein: 10, carbs: 46, fat: 12, fiber: 2, sugar: 40, sodium: 150, cat: 'Drinks' },
  { id: 'f207', name: 'Cheese Pizza', brand: 'Generic', serving: '1 slice', calories: 285, protein: 12, carbs: 36, fat: 10, fiber: 2, sugar: 4, sodium: 640, cat: 'Prepared' },
  { id: 'f208', name: 'Pepperoni Pizza', brand: 'Generic', serving: '1 slice', calories: 313, protein: 13, carbs: 36, fat: 13, fiber: 2, sugar: 4, sodium: 760, cat: 'Prepared' },
  { id: 'f209', name: 'Hamburger, fast food', brand: 'Generic', serving: '1 burger', calories: 540, protein: 25, carbs: 45, fat: 27, fiber: 2, sugar: 9, sodium: 950, cat: 'Prepared' },
  { id: 'f210', name: 'Chicken Noodle Soup', brand: 'Generic', serving: '1 cup', calories: 90, protein: 6, carbs: 12, fat: 2, fiber: 1, sugar: 1, sodium: 890, cat: 'Prepared' },
  { id: 'f211', name: 'Tomato Soup', brand: 'Generic', serving: '1 cup', calories: 110, protein: 2, carbs: 22, fat: 2, fiber: 2, sugar: 12, sodium: 690, cat: 'Prepared' },
  { id: 'f212', name: 'PB&J Sandwich', brand: 'Generic', serving: '1 sandwich', calories: 378, protein: 12, carbs: 48, fat: 16, fiber: 5, sugar: 17, sodium: 440, cat: 'Prepared' },
  { id: 'f213', name: 'Grilled Cheese', brand: 'Generic', serving: '1 sandwich', calories: 400, protein: 15, carbs: 30, fat: 25, fiber: 1, sugar: 4, sodium: 900, cat: 'Prepared' },
  { id: 'f214', name: 'Turkey Club Sandwich', brand: 'Generic', serving: '1 sandwich', calories: 480, protein: 30, carbs: 46, fat: 20, fiber: 3, sugar: 6, sodium: 1300, cat: 'Prepared' },
  { id: 'f215', name: 'Caesar Salad with Chicken', brand: 'Generic', serving: '1 salad', calories: 440, protein: 35, carbs: 14, fat: 27, fiber: 3, sugar: 3, sodium: 1000, cat: 'Prepared' },
  { id: 'f216', name: 'Chicken Quesadilla', brand: 'Generic', serving: '1 quesadilla', calories: 520, protein: 27, carbs: 40, fat: 28, fiber: 3, sugar: 3, sodium: 1050, cat: 'Prepared' },
  { id: 'f217', name: 'Pad Thai with Chicken', brand: 'Generic', serving: '1.5 cups', calories: 570, protein: 25, carbs: 65, fat: 22, fiber: 3, sugar: 15, sodium: 1350, cat: 'Prepared' },
  { id: 'f218', name: 'Chicken Curry with Rice', brand: 'Generic', serving: '1.5 cups', calories: 540, protein: 28, carbs: 62, fat: 19, fiber: 4, sugar: 8, sodium: 890, cat: 'Prepared' },
  { id: 'f219', name: 'Protein Pancakes', brand: 'Generic', serving: '3 pancakes', calories: 270, protein: 24, carbs: 32, fat: 5, fiber: 3, sugar: 6, sodium: 420, cat: 'Breakfast' },
  { id: 'f220', name: 'Burrito Bowl, veggie', brand: 'Generic', serving: '1 bowl', calories: 520, protein: 15, carbs: 78, fat: 17, fiber: 15, sugar: 6, sodium: 1100, cat: 'Prepared' },
]


export const MEAL_SLOTS = ['Breakfast', 'Lunch', 'Dinner', 'Snacks', 'Late Night']
