// Each skate discipline has its own MET-based calorie model and its own
// headline stats, because a hockey practice is not a trail cruise.
export const SKATE_TYPES = [
  {
    id: 'outdoor-fitness',
    name: 'Outdoor Fitness',
    emoji: '🛼',
    blurb: 'Steady aerobic session. The bread and butter.',
    met: 9.5,
    color: 'volt',
    stats: ['Distance', 'Avg Speed', 'Active Minutes'],
    gpsBased: true,
  },
  {
    id: 'trail',
    name: 'Trail',
    emoji: '🌲',
    blurb: 'Long paths, greenways, rail trails.',
    met: 9.0,
    color: 'volt',
    stats: ['Distance', 'Elevation Gain', 'Longest Segment'],
    gpsBased: true,
  },
  {
    id: 'urban',
    name: 'Urban',
    emoji: '🏙️',
    blurb: 'Stop-and-go city skating, curbs and crosswalks.',
    met: 8.0,
    color: 'surge',
    stats: ['Distance', 'Stops', 'Active Minutes'],
    gpsBased: true,
  },
  {
    id: 'speed',
    name: 'Speed Training',
    emoji: '⚡',
    blurb: 'Intervals and tempo work. High output.',
    met: 12.5,
    color: 'ember',
    stats: ['Top Speed', 'Avg Speed', 'Laps'],
    gpsBased: true,
  },
  {
    id: 'aggressive',
    name: 'Aggressive',
    emoji: '🤘',
    blurb: 'Park and street. Grinds, airs, bruises.',
    met: 10.0,
    color: 'ember',
    stats: ['Active Minutes', 'Tricks Landed', 'Calories'],
    gpsBased: false,
  },
  {
    id: 'hockey',
    name: 'Hockey Practice',
    emoji: '🏒',
    blurb: 'Drills, scrimmage, sprints, stops.',
    met: 11.0,
    color: 'surge',
    stats: ['Active Minutes', 'Sprints', 'Calories'],
    gpsBased: false,
  },
  {
    id: 'freestyle',
    name: 'Freestyle',
    emoji: '🎯',
    blurb: 'Slalom, cones, footwork, control.',
    met: 7.0,
    color: 'surge',
    stats: ['Active Minutes', 'Cone Runs', 'Calories'],
    gpsBased: false,
  },
  {
    id: 'commute',
    name: 'Commute',
    emoji: '🎒',
    blurb: 'Getting somewhere. Movement that counts.',
    met: 8.5,
    color: 'volt',
    stats: ['Distance', 'Duration', 'Calories'],
    gpsBased: true,
  },
  {
    id: 'recovery',
    name: 'Recovery',
    emoji: '🌿',
    blurb: 'Easy roll. Keeps the streak, spares the legs.',
    met: 5.5,
    color: 'surge',
    stats: ['Duration', 'Avg Speed', 'Active Minutes'],
    gpsBased: true,
  },
]

export const getSkateType = (id) =>
  SKATE_TYPES.find((t) => t.id === id) || SKATE_TYPES[0]
